services:
  docs:
    image: django_sandbox_local_docs
    container_name: django_sandbox_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_sandbox:/app/django_sandbox:z
    ports:
      - '9000:9000'
    command: /start-docs
